apiVersion: apps/v1
kind: Deployment
metadata:
  
spec:
  revisionHistoryLimit: 10
  template:
    metadata:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: label.jst.com/jiqi
                    operator: In
                    values:
                      - fh-product007
      containers:
          - image: registry-vpc.cn-zhangjiakou.aliyuncs.com/ruibo_prod/ruibo-oms-ruiboprod:3
            imagePullPolicy: Always
            name: ruibo-oms-prod
            ports:
              - containerPort: 7845
                name: p7845
                protocol: TCP
            resources:
              limits:
                cpu: '4'
                memory: 2Gi
              requests:
                cpu: '1'
                memory: 512Mi
            volumeMounts:
              - mountPath: /mnt/work/ruibo-oms/log
                name: log-path
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /mnt/work/ruibo_oms/log
            type: DirectoryOrCreate
          name: log-path