{
 "title": "Rocketmq_dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "broker tps & broker qps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_broker_tps" },
    { "expr": "rocketmq_broker_qps" }
   ]
  },
  {
   "title": "rocketmq_consumer_offset",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_consumer_offset" }
   ]
  },
  {
   "title": "rocketmq_consumer_message_size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_consumer_message_size" }
   ]
  },
  {
   "title": "rocketmq_producer_offset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_producer_offset" }
   ]
  },
  {
   "title": "rocketmq_consumer_tps",
   "type": "graph",
   "description": "消费tps",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_consumer_tps" }
   ]
  },
  {
   "title": "rocketmq_producer_message_size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_producer_message_size" }
   ]
  },
  {
   "title": "rocketmq_producer_tps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketmq_producer_tps" }
   ]
  },
  {
   "title": "rocketmq_group_get_latency_by_storetime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_group_get_latency_by_storetime"
    }
   ]
  },
  {
   "title": "rocketmq_message_accumulation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic)"
    }
   ]
  }
 ]
}