apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      #name: account
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: harbor.yingge.com/ops/account-wan:10
        imagePullPolicy: Always
        ports:
        - containerPort: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  type: NodePort
  selector:
    name: account
  ports:
  - port: 9200
    targetPort: 9200
    nodePort:
