apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  #namespace: default
  labels:
    app: mysql
data:
  my.cnf: |-
    [client]
    default-character-set=utf8mb4
    port            = 3306
    socket          = /tmp/mysql.sock
    
    [mysqld]
    bind-address = 0.0.0.0
    character_set_server = utf8mb4
    user = mysql
    port = 3306
    socket = /tmp/mysql.sock
    # basedir = /opt/mysql
    datadir = /data/mysql
    back_log = 1024
    max_allowed_packet = 32M
    net_read_timeout = 60
    wait_timeout = 28800
    interactive_timeout = 28800
    pid-file=/data/mysql/mysql.pid
    open_files_limit = 10240
    expire-logs-days = 3
    server-id=1
    log_bin=mysql_bin
    binlog_format = ROW
    
    # disable_ssl
    skip_ssl
    
    #skip-networking
    skip_name_resolve = 1
    max_connections = 4000
    max_connect_errors = 10000
    table_open_cache = 4096
    external-locking = FALSE
    binlog_cache_size = 2M
    max_heap_table_size = 256M
    read_buffer_size = 4M
    read_rnd_buffer_size = 16M
    sort_buffer_size = 32M
    join_buffer_size = 2M
    thread_cache_size = 64
    query_cache_size = 32M
    query_cache_limit = 2M
    query_cache_min_res_unit = 2k
    ft_min_word_len = 4
    
    #兼容sql语法
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION


---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: harbor.yingge.com/ops/mysql-wan:1.0
        #command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: MYSQL_ROOT_PASSWORD
          value: "JJeIJhB9Sxlh"
        - name: MYSQL_ROOT_HOST
          value: '%'
        volumeMounts:
        #- mountPath: /var/lib/mysql
        #  name: model-db-storage
        - name: config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
      volumes:
      #- name: model-db-storage
      #  persistentVolumeClaim:
      #    claimName: model-db-pv-claim
      - name: config      
        configMap:
          name: mysql
      - name: localtime
        hostPath:
          type: File
          path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    name: mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort:
